node ('contdocker') {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '9d3a660c-2923-4703-8337-28017b88e6e8') {
       def app = docker.build("poyaskov/docker-demo:${commit_id}", '.').push()
     }
   }
}
